services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: venda_veiculos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
